apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-jobber-operator

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-jobber-operator
  labels:
    app: k8s-jobber-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: k8s-jobber-operator
  template:
    metadata:
      labels:
        app: k8s-jobber-operator
    spec:
      serviceAccountName: k8s-jobber-operator
      containers:
      - name: k8s-jobber-operator
        image: vaizki/k8s-jobber:0.0.1
        command: [ "kopf", "run", "-n", "default", "/app/k8s_jobber.py" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-jobber-operator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list","watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get","list","watch","update","patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-jobber-operator
subjects:
- kind: ServiceAccount
  name: k8s-jobber-operator
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: k8s-jobber-operator
  apiGroup: rbac.authorization.k8s.io